/**
 * `@ghost/daemon` — the local process that hosts a user's ghosts.
 *
 * The binary is `ghostd` (`src/main.ts`); everything below is the library
 * surface, so a UI shell or a test can drive the same pieces in-process.
 */
export {
  API_TOKEN_FILENAME,
  API_TOKEN_PATTERN,
  apiTokenCommand,
  apiTokenMatches,
  defaultApiTokenPath,
  readApiToken,
  readOrCreateApiToken,
  rotateApiToken,
  type ApiTokenStoreOptions,
} from "./api-token.js";
export {
  createTokenStore,
  TOKEN_PATTERN,
  tokenMatches,
  type TokenCommandOptions,
  type TokenStore,
  type TokenStoreOptions,
  type TokenStoreSpec,
} from "./token-store.js";
export {
  ANTHROPIC_EXTRA_USAGE_NOTE,
  bindDefaultChatModelIfUnset,
  LoginManager,
  type LoginManagerOptions,
  type LoginPromptView,
  type LoginRuntime,
  type LoginStatus,
  type LoginView,
  type ProviderInfo,
} from "./auth.js";
export {
  assertLoopback,
  DEFAULT_GHOSTS_DIRNAME,
  DEFAULT_HOST,
  DEFAULT_PORT,
  defaultConfigPath,
  loadConfig,
  type DaemonConfig,
  type DaemonConfigFile,
  type DaemonConfigOverrides,
} from "./config.js";
export {
  CLAUDE_CODE_BINARY_ENV,
  CLAUDE_CODE_DEFAULT_MODEL_ID,
  CLAUDE_CODE_PROVIDER_ID,
  ClaudeCodeProcessError,
  ClaudeCodeRuntime,
  claudeSessionMetadataPath,
  isClaudePlanAuth,
  readClaudeCodeAuthStatus,
  resolveClaudeCodeExecutable,
  type ClaudeCodeAuthStatus,
  type ClaudeCodeQueryFactory,
  type ClaudeCodeRuntimeOptions,
  type ClaudeSessionMetadata,
} from "./claude-code.js";
export {
  createClaudePiMessagesAdapter,
  type ClaudePiMessagesAdapter,
} from "./claude-pi-messages.js";
export {
  findProviderCredentialEnv,
  PI_OFFLINE_ENV_VAR,
  PROVIDER_CREDENTIAL_ENV_PATTERNS,
  PROVIDER_CREDENTIAL_ENV_VARS,
  PROVIDER_ROUTING_ENV_VARS,
  scrubProviderEnv,
  type ScrubOptions,
  type ScrubResult,
} from "./env-scrub.js";
export {
  CREATOR_SCOPE,
  isVisitorScope,
  readGhostHomeDigest,
  resolveGhostExtensions,
  resolveGhostScope,
  visitorScope,
  type GhostExtensionOptions,
  type GhostHomeDigest,
  type GhostScope,
  type ResolvedGhostExtensions,
} from "./extensions.js";
export {
  assertValidGhostName,
  GHOST_AGENT_DIRNAME,
  GHOST_CHARACTER_FILENAME,
  GHOST_SESSIONS_DIRNAME,
  GhostError,
  GhostRegistry,
  ghostPaths,
  isGhostHome,
  isSeededCharacter,
  isValidGhostName,
  readCharacterFile,
  type Ghost,
} from "./ghosts.js";
export {
  buildGreetingContext,
  cleanGreeting,
  FIRST_MEETING_SECTION,
  generateGreeting,
  GREETING_CACHE_TTL_MS,
  GREETING_LEAK_MARKERS,
  GREETING_TIMEOUT_MS,
  GreetingCache,
  localTimeString,
  MAX_GREETING_CHARS,
  wholeDaysSince,
  type GenerateGreetingInput,
  type GreetingCacheOptions,
  type GreetingContextInput,
  type GreetingResult,
} from "./greeting.js";
export {
  defaultGhostHooksPath,
  GHOST_HOOK_HANDLER_TIMEOUT_MS,
  GHOST_SESSION_STOP_CONTINUATION_CAP,
  GhostHookRunner,
  ghostSessionStopContinuation,
  type GhostBeforePromptEvent,
  type GhostBeforePromptHandler,
  type GhostBeforePromptResult,
  type GhostHookAPI,
  type GhostHookContext,
  type GhostHookEvent,
  type GhostHookFactory,
  type GhostHookResult,
  type GhostSessionStopEvent,
  type GhostSessionStopHandler,
  type GhostSessionStopResult,
} from "./hooks.js";
export { createLogger, silentLogger, type Logger, type LogLevel } from "./log.js";
export {
  DEFAULT_MODELS_LIMIT,
  MAX_MODELS_LIMIT,
  ModelCatalog,
  type CatalogModel,
  type CurrentModel,
  type ListModelsQuery,
  type ListModelsResult,
  type ModelCatalogOptions,
  type ModelListItem,
  type ModelScope,
  type ModelView,
  type SetModelResult,
} from "./model-catalog.js";
export {
  AUTH_FILENAME,
  builtinProviderPreset,
  ghostAuthPath,
  ghostModelsLockPath,
  ghostModelsPath,
  GhostModelsLockError,
  GhostModelsWriteConflictError,
  MODELS_FILENAME,
  OPENROUTER_BASE_URL,
  OPENROUTER_DEFAULT_FREE_MODEL,
  OPENROUTER_PROVIDER_ID,
  openAiCompatiblePreset,
  openRouterPreset,
  readGhostModels,
  resolveChatModelRef,
  resolveSmolModelRef,
  writeGhostModels,
  type GhostModelDefinition,
  type GhostModelRole,
  type GhostModelRoleBinding,
  type GhostModelsFile,
  type GhostProviderConfig,
} from "./models.js";
export {
  createPiMessagesAdapter,
  encodeSseEvent,
  parsePiMessagesRequest,
  PiMessagesRequestError,
  SSE_HEADERS,
  SSE_KEEPALIVE_COMMENT,
  SSE_KEEPALIVE_INTERVAL_MS,
  textFromParts,
  zeroUsage,
  type PiMessagesAdapter,
  type PiMessagesAdapterOptions,
  type PiMessagesEvent,
  type PiMessagesRequest,
} from "./pi-messages.js";
export {
  attachRelay,
  createRelayHub,
  RELAY_CLOSE_GOING_AWAY,
  RELAY_PING_INTERVAL_MS,
  RELAY_TIMEOUT_GRACE_MS,
  RelayHub,
  type RelayHubOptions,
  type RelayStatus,
} from "./relay.js";
export {
  authorizeRelayUpgrade,
  encodeServerFrame,
  isRelayOp,
  MAX_FRAME_BYTES,
  parseClientFrame,
  RELAY_OPS,
  RELAY_PATH,
  RELAY_PROTOCOL_VERSION,
  RELAY_SUBPROTOCOL,
  RELAY_TOKEN_SUBPROTOCOL_PREFIX,
  type ParsedClientFrame,
  type RelayClientFrame,
  type RelayRequestFrame,
  type RelayServerFrame,
  type RelayUpgradeDecision,
} from "./relay-protocol.js";
export {
  defaultRelayTokenPath,
  readOrCreateRelayToken,
  readRelayToken,
  RELAY_TOKEN_FILENAME,
  relayTokenCommand,
  relayTokenMatches,
  rotateRelayToken,
  type RelayTokenStoreOptions,
} from "./relay-token.js";
export {
  createDaemonServer,
  relayHubOf,
  startDaemonServer,
  type ListeningServer,
  type ServerOptions,
} from "./server.js";
export {
  conversationIdFromSessionFile,
  DEFAULT_TRANSCRIPT_LIMIT,
  MAX_TRANSCRIPT_LIMIT,
  PI_BUILTIN_TOOL_NAMES,
  SessionHost,
  sessionFileNameFor,
  type GhostSessionHandle,
  type GreetingConfig,
  type GreetingGenerator,
  type RunTurnOptions,
  type SessionHostOptions,
  type SessionSummary,
  type TitleConfig,
  type TitleGenerator,
  type Transcript,
  type TranscriptMessage,
} from "./session-host.js";
export {
  assistantText,
  effectiveInputCost,
  rankSmolModels,
  resolveSmolModel,
  SMOL_MODEL_ROLE,
  smolCatalogFromRuntime,
  smolModelLabel,
  SmolModelUnavailableError,
  type ResolvedSmolModel,
  type SmolCandidate,
  type SmolModel,
  type SmolModelCatalog,
  type SmolRuntime,
} from "./smol.js";
export {
  buildTitleContext,
  cleanTitle,
  generateTitle,
  TITLE_PROMPT,
  type GenerateTitleInput,
} from "./title.js";
